import "./globals.css";
export const metadata = {
  title: "Codebin Editor",
  description: "Generated by create next app",
};

export default function NewPageLayout({ children }) {
  return (
    <>
      <main className="min-h-[100vh]">{children}</main>;
    </>
  );
}
